defaults:
 - override hydra/help: dlio_benchmark_help.yaml
 
app_name: dlio_benchmark

output_folder: "./output"

model:
  name: test

framework: pytorch

workflow:
  generate_data: True
  train: True
  evaluation: True

dataset: 
  data_folder: ./data/default/
  format: npz
  num_files_train: 64
  num_files_eval: 4
  num_samples_per_file: 1
  batch_size: 4
  batch_size_eval: 1
  file_access: multi
  record_length: 1145359

data_reader: 
  data_loader: pytorch

train:
  epochs: 10
  computation_time: 1.0

evaluation:
  eval_time: 0.5

